title: Large Language Models Yield Unsustainable Tourist Flows
subtitle: Testing Algorithmic Biases Using the Baseline-Rescaling-Outcome Model
author:
  - name: Seonjin Lee
    email: seonjin@sc.edu
    orcid: 0000-0002-3944-0738
    affiliations: 
      - id: smartstate
        name: Richardson Family SmartState Center for Economic Excellence in Tourism and Economic Development
        department: School of Hospitality and Tourism Management, University of South Carolina
        address: 1705 College St.
        city: Columbia
        state: SC
        country: USA
        postal-code: 29208
    corresponding: true
  - name: Lori Pennington-Gray
    email: penninl@mailbox.sc.edu
    affiliations:
      - ref: smartstate
abstract:
  Despite widespread adoption of generative AI in tourism, empirical evidence on its impacts are scarce.
  This study shows how large language models deviate from empirical tourism patterns, attributing the deviations to popularity biases.
  We propose Baseline-Rescaling-Outcome Model to test four types of popularity biases in AI-generated tourism recommendations.
  Large language models tend to produce more seasonal, more unequal, and less diversified tourist flows.
  These models also favoring popular destination-month pairs, but show mixed results for other popularity biases.
  Findings show that the widespread adoption of generative AI can undermine the sustainability and resilience of tourism systems.
  Thus, urge tourism scholars and practitioners to proactively assess generative AI biases and their consequences in tourism.
keywords: 
  - generative AI impact
  - tourist flow network
  - algorithmic bias
  - large language model simulation
  - tourism sustainability
  - tourism resilience
  
date: last-modified
format:
  apaquarto-docx: 
    floatsintext: true
    header-includes: 
      - \usepackage{placeins}
      - \usepackage{float}
    fig-format: svg
    fig-dpi: 300
    reference-doc: resources/custom.docx
  apaquarto-pdf:
    documentmode: doc
    journal: SocArXiv
    floatsintext: true
    header-includes: 
      - \usepackage{placeins}
      - \usepackage{float}
      - \usepackage{setspace}
      - \doublespacing
fig-width: 12
fig-height: 7
execute:
  echo: false
  warning: false
  message: false
  error: false
bibliography: references.bib
csl: apa.csl
