title: Large Language Models Yield Unsustainable Tourist Flows
author:
  - name: Seonjin Lee
    email: seonjin@sc.edu
    orcid: 0000-0002-3944-0738
    affiliations: 
      - id: smartstate
        name: Richardson Family SmartState Center for Economic Excellence in Tourism and Economic Development
        department: School of Hospitality and Tourism Management, University of South Carolina
        address: 1705 College St.
        city: Columbia
        state: SC
        country: USA
        postal-code: 29208
    corresponding: true
  - name: Lori Pennington-Gray
    email: penninl@mailbox.sc.edu
    affiliations:
      - ref: smartstate
abstract:
  While generative AI is increasingly affecting decisions in the tourism sector, we lack empirical evidence on its impact on tourism.
  This study quantifies how large language models and empirical tourism patterns differ in destination choices.
  The differences are explained using popularity biases in algorithms that favor popular options and pairs of options.
  We propose the Baseline-Rescaling-Outcome Model that tests four types of popularity biases in tourism.
  Large language models tend to produce more seasonal, more unequal, and less diversified tourist flows.
  We also find evidence of large language models favoring popular destination-month pairs.
  Findings show that the widespread adoption of generative AI can undermine the sustainability and resilience of tourism systems.
  We urge tourism scholars and practitioners to proactively assess the consequences of adopting generative AI in tourism.
keywords: 
  - generative AI impact
  - tourist flow network
  - algorithmic bias
  - large language models
  - network simulation
  - tourism sustainability
  
date: last-modified
format:
  apaquarto-docx: 
    floatsintext: true
    header-includes: 
      - \usepackage{setspace}
      - \usepackage{placeins}
      - \usepackage{float}
      - \doublespacing
    fig-format: svg
    fig-dpi: 300
  apaquarto-pdf:
    documentmode: doc
    journal: SocArXiv
    floatsintext: true
    header-includes: 
      - \usepackage{placeins}
      - \usepackage{float}
fig-width: 12
fig-height: 7
execute:
  echo: false
  warning: false
  message: false
  error: false
bibliography: references.bib
csl: apa.csl
